added Apps
kbaseapps/kb_ObjectUtilities pull request #3
Opened 2023-08-25 21:32 UTC by dcchivian

KButil_copy_object
KButil_count_ws_objects
KButil_update_genome_species_name

2023-09-10 05:26 UTC, cshenry commented
This looks good, although I have many suggestions you might consider in the future. That said, I don't think it should hold up this release. 

1.) Consider using parameter groups with the copy objects app so users could copy multiple objects at once. Not a huge deal. Could also consider reading in a file... but that's sketchier. More importantly, consider letting users specify the narrative ID to copy to... most useful if you make this an app that can do bulk. This could be optional... but that would make this app way better (the pull options in the data panel are bad for anyone with alot of data).

2.) In count workspace object app, consider having example types using the placeholder text in diplay.yaml (I think).

3.) In species name app, consider switching the free text field to a taxonomy select? Maybe broaden this app to a more powerful general editor that can change other fields. It does seem weird to let the user change species without changing taxonomy or domain. Seems like you can introduce errors this way. Thoughts on this?

4.) Alot of the genome editing utility functions seem somewhat redundant. The "files" version of the function seems to cover the others. Meanwhile, the files function seems strange to have a separate field for each parameter you want to change. Why not have a single file with the field being changes specified in the head (e.g. GenomeID    SpeciesName    Domain)?

5.) I'll note I would like to see functionality like this organized much better. The genome utilities really belong in a sort of genome API module. The MSA app and utility likewise should be in an MSA API module. This module, long term, really should focus on just the workspace object utilities.. like the count and copy apps. Even there, the name could probably be improved... maybe consider combining with the object info module module under a more general name.

2023-09-10 16:28 UTC, dcchivian commented
Thanks for the feedback Chris.  All good points.  Next iteration!

2023-09-10 16:29 UTC, merged

2023-09-11 18:16 UTC, psdehal requested changes
A couple typos to fix, also, in the impl file, you should add a "TODO" comment to tell the next dev to move the print/debug statement to logger

2023-09-11 18:16 UTC, psdehal commented on lib/kb_ObjectUtilities/kb_ObjectUtilitiesImpl.py
>  import requests
This was already imported above

2023-09-11 18:16 UTC, psdehal commented on lib/kb_ObjectUtilities/kb_ObjectUtilitiesImpl.py
> +        [OBJID_I, NAME_I, TYPE_I, SAVE_DATE_I, VERSION_I, SAVED_BY_I, WSID_I, WORKSPACE_I, CHSUM_I, SIZE_I, META_I] = range(11)  # object_info tuple
This gets cut and pasted into each of the functions. It could get moved out to the class level and defined as constants.

2023-09-11 18:16 UTC, psdehal commented on lib/kb_ObjectUtilities/kb_ObjectUtilitiesImpl.py
> +            raise ValueError('at least one of {} parameter is required'.format(",".join(at_least_one_param)))
typo, this should be 'at_least_one_params'

2023-09-11 18:16 UTC, psdehal commented on lib/kb_ObjectUtilities/kb_ObjectUtilitiesImpl.py
> +            raise ValueError('at least one of {} parameter is required'.format(",".join(at_least_one_param)))
typo, should be at_least_one_params

2023-09-11 19:06 UTC, dcchivian commented on lib/kb_ObjectUtilities/kb_ObjectUtilitiesImpl.py
> +            raise ValueError('at least one of {} parameter is required'.format(",".join(at_least_one_param)))
fixed

2023-09-11 19:07 UTC, dcchivian commented on lib/kb_ObjectUtilities/kb_ObjectUtilitiesImpl.py
> +            raise ValueError('at least one of {} parameter is required'.format(",".join(at_least_one_param)))
fixed

2023-09-11 19:09 UTC, dcchivian commented on lib/kb_ObjectUtilities/kb_ObjectUtilitiesImpl.py
>  import requests
fixed